### ISSUE TITLE
`:QuartoPreview` drops into insert mode because of user-defined TermOpen autocommand

### ISSUE THREAD

**Issue by AndyMcAliley** [quarto-dev/quarto-nvim#119]
When I call `:QuartoPreview`, the mode changes from normal to insert mode. The reason is that I have this line of vimscript in my config: `autocmd TermOpen * startinsert`, which is handy because I can start typing a command right away after `:term`. It's only a minor annoyance, but I wonder if there's a way to have my cake and eat it too?

What a wonderful plugin - thanks!

**Comment by jmbuhr** [comment]
I though about handling the preview in a process that is not tied to a terminal, but I prefer to give users the transparency and have it be a real terminal buffer. As such, there is nothing I can do about your autocommands. But what you can do is add the following to your config (after quarto, probably in the `after` directory):
```lua
api.nvim_create_user_command("QuartoPreview", function ()
  require'quarto'.quartoPreview()
  vim.cmd.stopinsert()
end, { nargs = "*" })
```

**Comment by jmbuhr** [comment]
I actually didn't know about `noautocmd`, thanks! However, I still prefer to leave it as is because some of those autocommands are actually wanted and I would like this to end up like a regular terminal buffer. For example, I have an autocommand to turn off line numbers in terminal buffers, but I can't make that decision for users.

If I where in your position, I would probably replace the terminal autocommand with a keybinding or usercommand that does those two things (opening the terminal and going into insert mode). We all have different preferences, but to me a mode change in an autocommand seems out of place for some reason.

**Comment by AndyMcAliley** [comment]
Makes sense to let users' autocommands stand. And I like the advice to create a new command for opening a terminal and dropping into insert mode. I copied that autocommand from `:help :terminal`, but I think it does make more sense to leave the default behavior of `:terminal` alone. 

Thanks again!
