### ISSUE TITLE
Windows error for Quarto Preview

### ISSUE THREAD

**Issue by FreeFlyFall** [quarto-dev/quarto-nvim#34]
I've switched to working with this in powershell on Windows. When I try to use quarto preview, I'm getting this error in a new Neovim tab:
> ERROR: The filename, directory name, or volume label syntax is incorrect. (os error 123), stat ''C:\path\to\file.qmd''

with the quotations being double apostrophes. I'm not sure where that's handled, to be able to change how it works. For now, my workaround is to add a which-key binding like:
> q = { "\<cmd\>!start quarto preview %:p\<cr\>", "Quarto preview this file"},

The "start" opens the command in a new shell so that control isn't taken from neovim.

**Comment by jmbuhr** [comment]
Interesting. I am assuming the error display adds one additional single quote around the already quoted filepath because I am only adding a literal single quote around the path here:
https://github.com/quarto-dev/quarto-nvim/blob/0f2b3f6f0e1a856378f0fd6551d45d16920089fd/lua/quarto/init.lua#L39

(The `\` escapes one single quote. I could clean this code up, since lua has three different string delimiters (`"`, `'` and `[[`), but this should'nt make a difference)

Interestingly, all combinations work when just called in powershell and not from within nvim, so I am assuming there is some interaction between the internal neovim terminal command and powershell:

https://github.com/quarto-dev/quarto-nvim/blob/0f2b3f6f0e1a856378f0fd6551d45d16920089fd/lua/quarto/init.lua#L55

**Comment by jmbuhr** [comment]
Maybe @jonathanvoelkle has an idea, they helped by adding installation instructions for windows to quarto-nvim-kickstarter.

**Comment by sho-87** [comment]
@jmbuhr I managed to get this working by not quoting `buffer_path` at all:

`cmd = 'quarto preview ' .. buffer_path`

happy to make a PR, but I'm not sure if this breaks anything on non-Windows machines

**Comment by jmbuhr** [comment]
Oh, that's annoying, we added the single quotes precisely because of the spaces (https://github.com/quarto-dev/quarto-nvim/pull/22)

I wonder if there is some option that messes up the quotes when passed to powershell. Maybe one of `:h shellquote`, `shellslash`, `shellxquote` or `shellxescape`?

Or, even simpler, would it work with double quotes `"` instead of single quotes?s

**Comment by sho-87** [comment]
setting it up with double quotes does get rid of the file path error, so that seems like a more sensible way to go:

`cmd = 'quarto preview "' .. buffer_path .. '"'`

but it leads a different error, which is kinda vague:

`ERROR: C:\Users\Simon\Desktop is not a project`

Not sure where that stems from. Seems more like an upstream issue?

**Comment by jmbuhr** [comment]
I believe what is happening is that the double quote stops PowerShell from reading further, or only the command up until the double quote is sent to the terminal. This would lead to the command missing the filepath and when quarto preview doesn't receive a filepath it looks for a _quarto.yml file in the current directory to render it as a project, but there is none. So the error is still in out shell quoting
