### ISSUE TITLE
r-language-server diagnostics being applied to markdown

### ISSUE THREAD

**Issue by fisher-j** [quarto-dev/quarto-nvim#46]
I'm on windows 10, using quarto-nvim-kickstarter. On write, diagnostics get applied to markdown sections as well as code chunks. 

![image](https://user-images.githubusercontent.com/63136705/229853415-4b7ffbc5-9989-48b7-a1ec-d6c629b09ed5.png)

**Comment by jmbuhr** [comment]
Check out the fix here: https://github.com/quarto-dev/quarto-nvim#r-diagnostics-configuration

But I do reallize that in the long run we would like to have a more elegant solution. I am also working on general (pretty big) performance improvements over at https://github.com/jmbuhr/otter.nvim/pull/26 and I right now diagnostic updates are still a slower part. If I can get those focussed on code chunk regions, it might solve two problems at the same time.

**Comment by fisher-j** [comment]
Thank you for your fast response.

I'm sure you are aware, but this appears to work already if I set ft to rmd. Is the above work trying to take advantage of the work thats been done on the treesitter markdown parser?

![image](https://user-images.githubusercontent.com/63136705/229863271-82c74aa2-d6b0-4fac-870c-947b1bcf9228.png)

**Comment by jmbuhr** [comment]
The main reason for the current approach is to provide the same capabilities to any language one might want to embed in quarto. For example, python and julia don't have their own plain-text computational notebook format, so their language servers don't work here. I think you are right for pure R users, using just the R language server on a quarto notebook will probably provide the best experience for now.

I actually plan to look into this this weekend.
Instead of setting the filetype to rmarkdown, you could also tell the R language server to also attach to quarto files like I do for the `marksman` language server (and tell the  quarto-nvim extension to not handle R chunks):

https://github.com/jmbuhr/quarto-nvim-kickstarter/blob/nightly/lua/plugins/quarto.lua#L160-L171
```
      lspconfig.marksman.setup {
        on_attach = on_attach2,
        capabilities = capabilities,
        filetypes = { 'markdown', 'quarto' },
        root_dir = util.root_pattern(".git", ".marksman.toml", "_quarto.yml"),
      }


      lspconfig.r_language_server.setup {
        on_attach = on_attach,
        capabilities = capabilities,
        flags = lsp_flags
      }
```

This would give you the best of both worlds.

**Comment by fisher-j** [comment]
Thanks for explaining the approach. After trying this out, I remember now why using rmd doesn't work: https://github.com/REditorSupport/languageserver/issues/609. Until that gets fixed, its not possible for me to used rmds in neovim with the language server.

**Comment by milanglacier** [comment]
> Thanks for explaining the approach. After trying this out, I remember now why using rmd doesn't work: [REditorSupport/languageserver#609](https://github.com/REditorSupport/languageserver/issues/609). Until that gets fixed, its not possible for me to used rmds in neovim with the language server.

You can directly disable diagnostics for r-lsp, which is easy:

```lua
    require('lspconfig').r_language_server.setup {
        settings = {
            r = {
                lsp = {
                    diagnostics = false, -- r-lsp + lintr is currently problematic
                },
            },
        },
    }

```
