### ISSUE TITLE
Language server not attached

### ISSUE THREAD

**Issue by fisher-j** [quarto-dev/quarto-nvim#47]
When I open a .qmd file, and run LSPInfo, I see there is no server attached, thus, the lsp functions (like document symbols, goto definition etc) do not work in Quarto files. Is this the expected behavior currently? If this is the expected behavior, are the other language server functionalities beyond completion and hover planned for implementation?

**Comment by fisher-j** [comment]
I do see that the server is attached to a hidden buffer. But because it is not attached to the qmd buffer, I don't get access to other language server functionality like `document symbols` and `goto definition`. Are these other server functionalities supposed to be made available through otter.nvim similar to completion?

**Comment by jmbuhr** [comment]
Document symbols is not currently implemented, as is e.g. rename symbol (https://github.com/jmbuhr/otter.nvim/issues/14).
`goto definition` should work though.
Currently I only have definition an hover implemented, see https://github.com/jmbuhr/otter.nvim/blob/02e9fe6b4f206dc1c79de059b32be136e7ddf269/lua/otter/init.lua#L14

Implementing new lsp actions is fairly straightforward but needs some consideration as to what parts of the lsp response have to changed. I would be very happy about PRs to `otter.nvim` with more of those! Each action needs the request to send to the language server, a filter (=a function that takes the lsp response and applies some edit to it, like in the case of go-to-definition to replace any mention of the language buffer with the corresponding main quarto buffer so that we jump to the correct place if it was defined in quarto but still jump to other files if it was defined elsewher), and lastly a fallback function that is being called when not inside of a language context (this is usually the default `vim.lsp.buf....` function.

**Comment by fisher-j** [comment]
Ok, thank you again for the explanation. I'm not sure I'm up to the task of implementing these, although it would be nice to have. Hopefully some _otters_ with more experience than me will catch on and start submitting PR's :)

**Comment by jmbuhr** [comment]
Which lsp features do you use most? 🦦

**Comment by fisher-j** [comment]
I use document symbols a lot when an analysis gets long. Signature help is also quite nice.

**Comment by jmbuhr** [comment]
I added this to my todo's (https://github.com/quarto-dev/quarto-nvim/issues/44), so I'll close this issue.

**Comment by fisher-j** [comment]
Thank you!

**Comment by jmbuhr** [comment]
@fisher-j I just added two commands that you might like: `QuartoSendAbove` and `QuartoSendAll` to send the code of the  language of the current code chunk to `vim-slime` (see kickstarter config)

**Comment by jmbuhr** [comment]
@fisher-j you can now use `gr` to show all references for a symbol and `<leader>lR` to rename a symbol :)
