### ISSUE TITLE
E5113: Error while calling lua chunk: vim/_meta.lua:659: Not a valid option name: winbar

### ISSUE THREAD

**Issue by armandfavrot** [quarto-dev/quarto-nvim#48]
After cloning the Kickstarter repository, I got this error when executing nvim:

E5113: Error while calling lua chunk: vim/_meta.lua:659: Not a valid option name: winbar
stack traceback:
        [C]: in function 'assert'
        vim/_meta.lua:659: in function 'make_option'
        vim/_meta.lua:723: in function '__newindex'
        /home/armand/.config/nvim/lua/config/global.lua:56: in main chunk
        [C]: in function 'require'
        /home/armand/.config/nvim/init.lua:1: in main chunk

**Comment by jmbuhr** [comment]
I believe the `winbar` option was introduced in neovim 0.8., so I am assuming your version is older. Is that correct? You can download it from the releases here: https://github.com/neovim/neovim/releases.

However, as you can also see there, the latest version `0.9.0` was released a couple of hours again!
This version requires some changes to the internals of the `otter.nvim` plugin that keeps track of our codeblocks for quarto-nvim due to updates in the `treesitter` module. I address theses changes here: https://github.com/jmbuhr/otter.nvim/pull/26.

The version of the kickstarter repo that I use to test these updates is here: https://github.com/jmbuhr/quarto-nvim-kickstarter/pull/17  but right now it is still specifying the local version of theses plugins on my machine. Now that nvim 0.9 is out I will finalize those changes and prepare the branch for testing, so you may want to try this tomorrow :)

**Comment by armandfavrot** [comment]
After trying the Kickstarter, I tried to get back to my older nvim configuration but I couldn't make it work, I think due to the fact that I removed the ~/.local/share/nvim folder.

I then uninstalled nvim before I saw your response so I cannot tell you what was my nvim version.

I now have the 0.9.0 version. (I still cannot get my old configuration to work because of PlugInstall which don't want to work..)

So I'm currently trying the kickstarter, it seems to work, despite this problem during the installation : 

![fail_installation_kickstarter_quarto_nvim](https://user-images.githubusercontent.com/81771007/230713853-7c1cba96-7285-41bb-be38-3c52b820391e.png)

I will try to follow your tutorials in youtube and I let you know if I have some issues.

Thanks very much for your help :)

**Comment by jmbuhr** [comment]
Thanks, happy to hear how it goes!
I'm expecting more of these kinds of messsages in the next couple of days, as more plugins have to update adjust to nvim 0.9. Additionally, since the kickstarter uses `lazy.nvim` for packages it will automatically get the latest tagged release of a plugin, which can be behind the main branch on which the changes may already be.
