### ISSUE TITLE
Official Molten support?

### ISSUE THREAD

**Issue by benlubas** [quarto-dev/quarto-nvim#93]
I'm wondering what you think of officially supporting [molten-nvim](https://github.com/benlubas/molten-nvim) as a code runner. Given Quarto's used as notebook style tool, running code with the Jupyter kernel seems like a great fit. 

I'm happy to do some work here if it would be welcome.

**Comment by jmbuhr** [comment]
I think that's a great idea and a good opportunity to properly define a configurable backend (molten, slime) for the QuartoSend family of functions.

Those already handle extracting the code from one or multiple chunks and all that we need is a function that takes a string or table of strings for sending. Though maybe executing multiple chunks may be handled differently with molten.

**Comment by jmbuhr** [comment]
We'll have to discuss what the default's should be, could also be dynamic depending on the document content. e.g. molten if it's installed and the document only contains python, slime if it contains only R, or a user defined default if set.

**Comment by benlubas** [comment]
a couple things to note here:

1. Molten is going to have a different interface for running code than slime I'd think. 
	- Molten needs line numbers, while slime will probably want the code that it should run. Molten needs lines so that it can create a 'cell' which is used to highlight code to indicate that there's output associate to it, and to position the output window.
	- I don't really see this as a problem, we can just make the quarto backend handle both. It's just something that we'll have to keep in mind.
2. Molten can run R as well. It can run anything with a Jupyter Kernel. As long as the kernel is installed, Molten should be able to see it.
	- [here](https://github.com/jupyter/jupyter/wiki/Jupyter-kernels) is a list of languages that Molten can theoretically run
3. Slime might have an edge when it comes to multi-language documents. If there's both python and R in the same document, and you'd want to send them to different kernels, there is currently no way to do that with Molten, that is something that I ultimately do want to add support for. But that's a little ways down the road I think

**Comment by benlubas** [comment]
After thinking about this further. I think I'm going to hold off on this work until I add multi language (for one buffer) capability to Molten.

Until then, if users would like image output and all the other benefits of molten I'd encourage them to use this [wiki post](https://github.com/benlubas/molten-nvim/wiki/Notebook-Setup)

**Comment by benlubas** [comment]
Alright, [multi kernel](https://github.com/benlubas/molten-nvim/pull/16) is ready to go, it's just waiting while I make sure there aren't any major bugs that I missed. 

So I'll start work on this!

**Comment by benlubas** [comment]
@jmbuhr what is the current state of quarto-nvim's code running capabilities? I see that there's vim slime, and yarepl, but it seems like the yarepl doesn't work, given we're calling `yarepl._send_strings(0)` and nothing else.

**Comment by jmbuhr** [comment]
oh, wow, multikernel is exciting!

I haven't followed up on yarepl because it doesn't really do anything we can't already do with vim-slime and neovim terminals. But if we set make the code runner backend configurable I might look into it again to give people the option.

I think all we have to do is add this config option and then make `send` https://github.com/quarto-dev/quarto-nvim/blob/14a80ffab90567e360eb97b19039c4c16913ad79/lua/quarto/init.lua#L166 respect it.

But do let me know what molten needs, as you said it keeps track of its own chunks.
Maybe you can also make use of the otter.keeper functions for getting code chunks around, before or after the cursor.
They are helpful because they respect `eval: false` when doing e.g. "run all chunks above".
Or maybe you need your own functionality.

**Comment by jmbuhr** [comment]
Maybe we can also directly make use of `otter.nvim`'s `otter.keeper.extract_code_chunks` for molten-nvim , since there we already have all the information we need about all code chunks (including respecting eval: false). This way we can avoid having to parse the document again for molten, when the code chunks are already known and treesiter has already done the parsing for otter.nvim anyways.

```lua
      local result = {
        range = { from = { row1, col1 }, to = { row2, col2 } },
        lang = lang_capture,
        node = node,
        text = lines(text),
      }

```

**Comment by benlubas** [comment]
Thanks! I think I'll definitely make use of otter's parsing, the `extract_code_chunks` table has all the information that I think any code runner should need to run the code, so that's perfect.

One question about that, does parse on keystroke or on write? Like would it always give me the code that's currently displayed, or only the code that's been most recently saved?

I'm hoping to introduce something that's very configurable and meets the following criteria:
- Support for running multiple languages within the same file
- `runAbove`/`runAll`/`runBelow` which can optionally respect the language of the code cell you're currently in
- Associating different languages to different code runners (say you want to run python with molten, but bash with slime). This would be useful in case a user wants to use Molten when they can, but also needs to run a language/repl that isn't supported by Molten.

And then I'd like to solve the issue of code sending when there are two repl's/kernels running at the same time. Currently it seems like with slime you'll get prompted with where you want to send the code when there's more than one option, Molten behaves in the same way. Molten (and hopefully slime too but idk) allows specifying a `kernel_id` to avoid the prompt and just send the code to the specified kernel. It would be great if quarto-nvim had some way of associating a certain language with a `kernel_id`. Maybe this association could be permanent (ie specified in the configuration) or temporal (ie. specified in some type of ui/command, and will be thrown out when neovim is closed). Would be great to have both.

This would allow the user to run two kernels, an `ipython` and an `ir`, tell quarto that `ir` is associated with the `r` programming language, and then every time after that, trying to run an `r` code block would automatically send the code to `ir`.

I think it would be best to not deal with initialization of kernels/repl's in quarto, as there are a wide range of ways that these code running plugins can be configured. And with Molten at least, there's no way to automatically initialize the correct kernel just by parsing the document and finding language information.

**Comment by jmbuhr** [comment]
I just realized I'm not globally storing the code chunks, which is something I'll implement so they are available for other plugins. But they will be up to date on keystroke if `completion` is turned on, because this calls `otter.keeper.sync_raft` on completion request to update the hidden otter buffers for which it also needs to get the latest code chunks
```lua
M.sync_raft = function(main_nr)
  if M._otters_attached[main_nr] ~= nil then
    local all_code_chunks = extract_code_chunks(main_nr)
```
I'll move the code chunks to something like `otter.keeper._otters_attached[main_nr].code_chunks` and make updating them a side effect of `extract_code_chunks` instead of only returning them. I can also use the opportunity to see if now is the time to implement a change tick so that the function can simply return early if the code chunks are already up to date :)

I had also thought of automatically switching between target terminals based on the current context, but haven't done so, yet. I already have `otter.keeper.get_current_language_context()` to get the language of the current code chunk.

**Comment by jmbuhr** [comment]
The main reason I haven't implemented automatic target switching is because if it where to be used with R and python, the correct thing to do would be to use an R terminal for R and a python repl embedded in R with the `reticulate` R package for python code. Because this is what happens when the document gets rendered (It's really cool, you can use variables and functions from R in python and the other way around)

**Comment by benlubas** [comment]
I did not know that, that's really interesting (can you tell I'm not a data scientist lol) . I still think that having auto target switching as an off-by-default-option would be nice, I could certainly see some use cases for it.

**Comment by jmbuhr** [comment]
Yes, certainly! I also use quarto documents extensively as notebooks to send lines to a mix of R, python and bash consoles that is not necessarily designed to be executed on render. Like keeping track of compilation instructions for software or writing tutorials where the user is also expected to run commands in different terminals.

**Comment by jmbuhr** [comment]
`otter.keeper._otters_attached[main_nr].code_chunks` are now available as of the latest release of https://github.com/jmbuhr/otter.nvim. To make sure they are up to date, call `otter.keeper.sync_raft` before using them. It will only parse again if the quarto buffer has changed since the last time they where updated.
https://github.com/jmbuhr/otter.nvim/blob/b25537cc5c836f1a485176757da954b775a5b914/lua/otter/keeper.lua#L147C9-L147C9
